# Generated by Django 4.2.15 on 2024-08-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.FileField(blank=True, upload_to="project_images/"),
        ),
    ]
